import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className="bg-[#0B1120] text-[#E5E7EB] min-h-screen"
        className="bg-gradient-to-r from-[#38BDF8] via-[#6366F1] to-[#8B5CF6]"
      >
        <Header></Header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
