import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//#b65d54 #800022 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-[#ffffea] text-[#800022] min-h-screen manrope-font"
      // className="bg-gradient-to-r from-[#38BDF8] via-[#6366F1] to-[#8B5CF6]"
      >
        <ToastContainer
          position="top-center"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        <Header></Header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
